export const SET_BREEDS_DATA = 'SET_BREEDS_DATA';
export const SET_BREED_ID = 'SET_BREED_ID';
export const SET_FAVORITE_BREEDS = 'SET_FAVORITE_BREEDS';
export const CLEAR_FAVORITE_BREEDS_STATE = 'CLEAR_FAVORITE_BREEDS_STATE';